Bashiru.com.PaymentGateway:

server:
  port : 8484

Spring:
  application:
    name: mtn-momo

Client:
  momo:
    target-environment: sandbox
    ocp-apim-subscription-key: 60d019174b8b449eb70cea8e24e3a5e6
    api-key: e43f5a49a5b34432b4089409b50f5982
    api-user-id: ffbd2ceb-06e4-46d6-bf80-bd09ec026d9a



